[theme]
primaryColor = "#7D4E57"           # Colour of buttons, sliders, and other interactive elements
backgroundColor = "#1D0064"        # Background colour of the app
secondaryBackgroundColor = "#130239"  # Background colour of cards, containers
textColor = "#ffdd9b"              # Main text colour
font = "sans serif"                # Font family, options: "sans serif", "serif", "monospace"
